"""empty message

Revision ID: 88faf57a31e7
Revises: 51f5ccfba190
Create Date: 2020-11-21 13:38:05.673600

"""

# revision identifiers, used by Alembic.
revision = '88faf57a31e7'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
